### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by klvnraju** [klvnraju/sequencediagrams-electron#2]
my own data
## Browser
- Name: 
- Version: 
- Platform: 
## User report
something

![screenshot](https://github.com/klvnraju/sequencediagrams-electron/blob/master/screenshot-1542627470288370832.png?raw=true)

**Comment by viradhamMS** [comment]
Good test
![image](https://user-images.githubusercontent.com/11805676/48707998-3f056d00-ec27-11e8-9474-6a7dd157ce8a.png)
